# Generated by Django 4.2.6 on 2023-12-15 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_vacancy_frameworks'),
        ('chat', '0003_chat_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='resume',
        ),
        migrations.AddField(
            model_name='chat',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.vacancy'),
        ),
    ]
