# Generated by Django 4.2.6 on 2023-12-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='employer',
            new_name='creator',
        ),
    ]
