# Generated by Django 4.2.6 on 2023-12-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_company_name_customuser_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
