# Generated by Django 4.2.6 on 2023-12-02 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Work Experience')),
                ('education', models.TextField(blank=True, null=True, verbose_name='Education')),
                ('social_links', models.TextField(blank=True, null=True, verbose_name='Social Links')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('languages', models.ManyToManyField(to='employee.language', verbose_name='Languages')),
                ('skills', models.ManyToManyField(to='employee.tag', verbose_name='Skills')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.tag')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('languages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.language')),
            ],
        ),
    ]
