# Generated by Django 4.2.6 on 2023-12-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritelanguage',
            old_name='job_seeker',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='favoritetag',
            old_name='job_seeker',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job_seeker',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='job_seeker',
            new_name='creator',
        ),
    ]
