# Generated by Django 4.2.6 on 2023-12-13 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_seeker', '0001_initial'),
        ('employee', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='resume',
            name='frameworks',
            field=models.ManyToManyField(to='employee.framework', verbose_name='Frameworks'),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.ManyToManyField(to='employee.language', verbose_name='Languages'),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(to='employee.tag', verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.vacancy'),
        ),
    ]
