# Generated by Django 4.2.6 on 2023-12-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_vacancy_frameworks'),
        ('job_seeker', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='frameworks',
            field=models.ManyToManyField(blank=True, to='employee.framework', verbose_name='Frameworks'),
        ),
    ]
